# Form implementation generated from reading ui file 'ds_main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(MainForm)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_inn = QtWidgets.QLineEdit(parent=MainForm)
        self.lineEdit_inn.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEdit_inn.setObjectName("lineEdit_inn")
        self.gridLayout.addWidget(self.lineEdit_inn, 1, 2, 1, 1)
        self.pushButton_choose_file = QtWidgets.QPushButton(parent=MainForm)
        self.pushButton_choose_file.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_choose_file.setObjectName("pushButton_choose_file")
        self.gridLayout.addWidget(self.pushButton_choose_file, 0, 3, 1, 1)
        self.pushButton_info = QtWidgets.QPushButton(parent=MainForm)
        self.pushButton_info.setObjectName("pushButton_info")
        self.gridLayout.addWidget(self.pushButton_info, 5, 0, 1, 2)
        self.label_inn = QtWidgets.QLabel(parent=MainForm)
        self.label_inn.setObjectName("label_inn")
        self.gridLayout.addWidget(self.label_inn, 1, 0, 1, 1)
        self.lineEdit_path = QtWidgets.QLineEdit(parent=MainForm)
        self.lineEdit_path.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.gridLayout.addWidget(self.lineEdit_path, 0, 2, 1, 1)
        self.label_file_path = QtWidgets.QLabel(parent=MainForm)
        self.label_file_path.setObjectName("label_file_path")
        self.gridLayout.addWidget(self.label_file_path, 0, 0, 1, 1)
        self.pushButton_ready = QtWidgets.QPushButton(parent=MainForm)
        self.pushButton_ready.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_ready.setObjectName("pushButton_ready")
        self.gridLayout.addWidget(self.pushButton_ready, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(parent=MainForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 4)
        self.pushButton_close = QtWidgets.QPushButton(parent=MainForm)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 5, 2, 1, 2)
        self.textEdit_output = QtWidgets.QTextEdit(parent=MainForm)
        self.textEdit_output.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.textEdit_output.setObjectName("textEdit_output")
        self.gridLayout.addWidget(self.textEdit_output, 3, 0, 1, 4)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "excel_papser"))
        self.pushButton_choose_file.setText(_translate("MainForm", "..."))
        self.pushButton_info.setText(_translate("MainForm", "О программе"))
        self.label_inn.setText(_translate("MainForm", "Введите ИНН"))
        self.label_file_path.setText(_translate("MainForm", "Выберите файл"))
        self.pushButton_ready.setText(_translate("MainForm", "Готово"))
        self.label.setText(_translate("MainForm", "Вывод:"))
        self.pushButton_close.setText(_translate("MainForm", "Закрыть"))
